server:
  port: 6666

camel:
  springboot:
    auto-startup: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camels
    username: root
    password: Pavilion@12




  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


